entry: event_handler
main: /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/memcached.c
hook: xdp
framework: libev
sources: [
    # /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/proto_bin.c,
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/proto_text.c,
]
_sources: [
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/assoc.c,
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/authfile.c,
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/base64.c,
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/bipbuffer.c,
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/cache.c,
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/crawler.c,
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/crc32c.c,
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/daemon.c,
    # /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/darwin_priv.c,
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/extstore.c,
    # /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/freebsd_priv.c,
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/globals.c,
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/hash.c,
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/items.c,
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/itoa_ljust.c,
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/jenkins_hash.c,
    # /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/linux_priv.c,
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/logger.c,
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/md5.c,
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/murmur3_hash.c,
    # /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/openbsd_priv.c,
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/proto_bin.c,
    # /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/proto_proxy.c,
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/proto_text.c,
    # /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/proxy_await.c,
    # /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/proxy_config.c,
    # /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/proxy_internal.c,
    # /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/proxy_jump_hash.c,
    # /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/proxy_lua.c,
    # /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/proxy_network.c,
    # /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/proxy_request.c,
    # /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/proxy_ring_hash.c,
    # /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/proxy_ustats.c,
    # /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/proxy_xxhash.c,
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/restart.c,
    # /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/sasl_defs.c,
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/sizes.c,
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/slab_automove.c,
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/slab_automove_extstore.c,
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/slabs.c,
    # /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/solaris_priv.c,
    # /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/stats_prefix.c,
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/storage.c,
    # /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/testapp.c,
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/thread.c,
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/timedrun.c,
    # /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/tls.c,
    /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/memcached/util.c,
]
out_bpf:
out_user:
cflags: '-I /home/farbod/auto_bpf_offload/auto_bpf_offload_case_study/src/'
